nameOverride: "cortex-demo"
fullnameOverride: "cortex-demo"
minio:
  mode: standalone ## other supported values are "standalone", "gateway"
  rootUser: "admin"
  rootPassword: "passw0rd"
  drivesPerNode: 1
  replicas: 1
  pools: 1
  tls:
    enabled: false
  persistence:
    enabled: true
    size: 1Gi
    subPath: ""
  ingress:
    enabled: false
  resources:
    requests:
      memory: 4Gi
