minio:
  fullnameOverride: minio
  mode: standalone
  rootUser: "admin"
  rootPassword: "passw0rd"
  drivesPerNode: 1
  replicas: 1
  pools: 1
  tls:
    enabled: false
  persistence:
    enabled: true
    size: 1Gi
    subPath: ""
  ingress:
    enabled: false
  resources:
    requests:
      memory: 4Gi
  buckets:
  - name: cortex-alertmanager-storage
    policy: none
  - name: cortex-blocks-storage
    policy: none
  - name: cortex-ruler-storage
    policy: none
cortex:
  config:
    alertmanager_storage:
      s3:
        region: us-east-1
        endpoint: minio:9000
        bucket_name: cortex-alertmanager-storage
        access_key_id: admin
        secret_access_key: passw0rd
        insecure: true
    storage:
      engine: blocks
    blocks_storage:
      backend: s3
      s3:
        region: us-east-1
        endpoint: minio:9000
        bucket_name: cortex-blocks-storage
        access_key_id: admin
        secret_access_key: passw0rd
        insecure: true
      bucket_store:
        sync_dir: "/data"
      tsdb:
        dir: "/data"
    querier:
      store_gateway_addresses: cortex-store-gateway-headless:9095
    ruler_storage:
      s3:
        region: us-east-1
        endpoint: minio:9000
        bucket_name: cortex-ruler-storage
        access_key_id: admin
        secret_access_key: passw0rd
        insecure: true
prometheus:
  rbac:
    create: false
  alertmanager:
    enabled: false
  configmapReload:
    prometheus:
      enabled: true
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false
  server:
    fullnameOverride: prometheus
    enabled: true
    name: server
    persistentVolume:
      enabled: false
  pushgateway:
    enabled: false
  serverFiles:
    prometheus.yml:
      rule_files:
      scrape_configs:
      - job_name: prometheus
        static_configs:
        - targets:
          - avalanche:9001
      remote_write:
      - url: http://cortex-nginx/api/v1/push
grafana:
  fullnameOverride: grafana
  rbac:
    create: false
  pspEnabled: false
  serviceAccount:
    create: false
  adminUser: admin
  adminPassword: passw0rd
  persistence:
    type: pvc
    enabled: false
    size: 100Mi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: cortex
        type: prometheus
        url: http://cortex-nginx/prometheus
        access: proxy
        isDefault: true
