apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche
  labels:
    name: avalanche
spec:
  selector:
    matchLabels:
      app: avalanche
  replicas: 1
  template:
    metadata:
      labels:
        app: avalanche
    spec:
      containers:
      - name: avalanche
        image: quay.io/prometheuscommunity/avalanche:main
        args:
        - "--metric-count=1000"
        - "--series-count=50"
        - "--label-count=10"
        - "--port=9001"
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: avalanche
  labels:
    app: avalanche
spec:
  ports:
  - port: 9001
    targetPort: 9001
    name: http-avalanche
  selector:
    app: avalanche