## Provide a name in place of minio for `app:` labels
##
nameOverride: "minio"

## Provide a name to substitute for the full names of resources
##
fullnameOverride: "minio"

## minio mode, i.e. standalone or distributed or gateway.
mode: standalone ## other supported values are "standalone", "gateway"


## Set default rootUser, rootPassword
## AccessKey and secretKey is generated when not set
## Distributed MinIO ref: https://min.io/docs/minio/linux/operations/install-deploy-manage/deploy-minio-multi-node-multi-drive.html
##
rootUser: "admin"
rootPassword: "passw0rd"

# Number of drives attached to a node
drivesPerNode: 1
# Number of MinIO containers running
replicas: 1
# Number of expanded MinIO clusters
pools: 1

## TLS Settings for MinIO
tls:
  enabled: false

persistence:
  enabled: true
  size: 1Gi
  subPath: ""

ingress:
  enabled: false

resources:
  requests:
    memory: 4Gi

